generator/templates/actions/actions.gotpl
generator/templates/actions/create.gotpl
generator/templates/actions/find.gotpl
generator/templates/actions/structs.gotpl
generator/templates/client.gotpl
generator/templates/query.gotpl
generator/test/basic/basic_test.go

Add godoc comments in templates and un-export most internal structs (for now).
This prevents external usage for now; we may undo this change later on,
although we don't know yet exactly what we want to expose because it is
mostly used internally. However, sometimes users may want to access these,
especially libraries building on top of Photon Go

docs(templates): improve godoc coverage

---

binaries/binaries.go
cli/cli.go
engine/engine.go
engine/lifecycle.go
generator/templates/client.gotpl
generator/templates/input.gotpl
logger/logger.go
main.go

When binaryTargets are provided, fail if no engine is found.

fix(engine): fail on binary targets

---

cli/cli.go

Allows overriding engines with the following environment variables:
- PRISMA_QUERY_ENGINE_BINARY
- PRISMA_MIGRATION_ENGINE_BINARY
- PRISMA_INTROSPECTION_ENGINE_BINARY

feat(cli): allow overriding engines with env vars

---

generator/templates/enums.gotpl

Fix newline issue where the next generated line would appear on the same line as the last `)`.

Ensure newline after generated enums

---

generator/templates/actions/create.gotpl
generator/test/types/schema.prisma
generator/test/types/types_test.go

This prefixes CreateOne params with an underscore and adds
test for a non-required reserved keyword schema field to
make sure the tests pass.
fix #91

test(types): prefix CreateOne params with an underscore

---

generator/templates/actions/actions.gotpl
generator/templates/client.gotpl
generator/templates/load.gotpl
generator/test/basic/basic_test.go
generator/test/load/load_test.go
generator/test/pagination/pagination_test.go
generator/test/relations/relations_test.go
generator/test/types/schema.prisma
generator/test/types/types_test.go

This prevents clashes with user-defined models named Client.
fix #93

fix(tpl/client): rename Client to PrismaClient

---

generator/templates/query.gotpl
generator/test/basic/basic_test.go

The SetOptional method is the same as the Set method but
takes a pointer instead to be able to specify nullable
values using pointers.
fix #106
fix #107

feat(client/create): add SetOptional methods

---

generator/templates/models.gotpl
generator/test/basic/basic_test.go
generator/test/pagination/pagination_test.go
generator/test/relations/relations_test.go
generator/test/types/types_test.go

Expose the internal struct and use a different internal
struct just for the relations.
Before, just one struct could be accessed, which is called `<model-name>Model`:
```go
user, err := client.User.FindOne().Exec(ctx)
handle(user)
func handle(user db.UserModel) {
if email, ok := user.Email(); ok {
log.Printf("email is set, its value is %s", email)
}
}
```
Even though we use methods to access optional fields and relations, the struct can still be (un)marshalled to/from json.
However, when you need to convert this data to another type of struct for any other library which uses type safe structs (e.g. gqlgen, grace-go), you need to convert between those structs manually. Since you would need to convert all fields one by one, especially the optional ones, this PR just exposes in the internal …

feat(tpl/models): expose internal struct

---

generator/templates/models.gotpl
test/projects/relations/relations_test.go
test/projects/relations/schema.prisma

Model relation methods return just one value, but if they're
optional they return (T, ok).

fix(tpl/models): adapt relation return signature

---

.dockerignore
binaries/platform/platform.go
docker/integration.dockerfile

feat(platforms): add alpine support

---

.github/workflows/test.yml
generator/dmmf/dmmf.go
generator/templates/actions/actions.gotpl
generator/templates/query.gotpl
generator/types/types.go
test/features/composite/default_test.go
test/features/composite/schema.prisma
test/setup/generate/generate.go
test/setup/init/setup.go

This also generates individual Equals() field types to
be able to constraint the composite input types down to the
individual field and operation.

feat(query): add composite FindOne params

---

docs/quickstart.md

Instead, use their defaults and simplify the quickstart guide.

docs(quickstart): remove generator options

---

.github/workflows/lint.yml

better wait for issues opened in the golangci-lint action https://github.com/golangci/golangci-lint-action/issues?q=is%3Aopen+is%3Aissue+author%3Asteebchen+sort%3Aupdated-desc

ci(lint): use golangci-lint github action

---

.github/workflows/lint.yml

switch to the cli because the old action doesn't support go generate and thus can't restore the cache properly

ci(lint): use golangcilint cli

---

docs/reference/07-delete.md

I just corrected a simple mistake on line 32, where was written "updated" instead of "deleted".
I love the documentation! Keep up the good work! I'm loving Prisma Client Go.

docs(reference): change "updated" to "deleted"

---

engine/protocol.go
engine/request.go
generator/raw/query_raw.go
generator/runtime/errors.go
generator/templates/_header.gotpl
generator/templates/actions/create.gotpl
generator/templates/actions/find.gotpl
generator/templates/actions/structs.gotpl
generator/templates/errors.gotpl

Refactor internal error handling by using a struct for just
`data` and `errors` to check for errors then unmarshal
`data` later. Cleanup a few minor things as well.
fix #278

fix(errors): refactor internal pql error handling

---

generator/templates/query.gotpl
test/features/link_many/link_test.go
test/features/link_many/schema.prisma

fix #285 
note: this doesn't work with composite keys yet; that'll be fixed in a separate PR

fix(query): link many relations in nested create/update

---

docs/quickstart.md
docs/reference/11-raw.md
generator/builder/builder.go
generator/lifecycle/lifecycle.go
generator/raw/execute_raw.go
generator/raw/query_raw.go
generator/raw/raw.go
generator/templates/_header.gotpl
generator/templates/client.gotpl
test/databases/mysql/raw/raw_deprecated_test.go
test/databases/mysql/raw/raw_test.go
test/databases/postgresql/raw/raw_test.go
test/integration/main.go

This deprecates Connect, Disconnect, QueryRaw and ExecuteRaw.
Instead, the new equivalent .Prisma.<Method> should be used.

feat(client): introduce prisma client namespace

---

runtime/raw/raw.go
test/databases/mysql/raw/raw_deprecated_test.go
test/databases/mysql/raw/raw_test.go
test/databases/mysql/raw/schema.prisma
test/databases/postgresql/raw/raw_test.go
test/databases/postgresql/raw/schema.prisma
test/databases/sqlite/raw/raw_test.go
test/databases/sqlite/raw/schema.prisma

The query engine expects time parameters in a special json
syntax because JSON doesn't have a time/date type.
fix #395

feat(raw): handle time values

---

generator/dummy.go
generator/templates/actions/dummy.go
generator/templates/dummy.go

This change is a no-op outside `go mod vendor` situations.
These are necessary to run but aren't included when vendoring this
library.  See also https://github.com/golang/go/issues/27832

fix: add dummy.go files to template dirs

---

.github/dependabot.yml

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#commit-message
> By default, Dependabot attempts to detect your commit message preferences and use similar patterns.

chore(project): enable dependabot version updates

---

test/features/transaction/transaction_test.go
test/features/transaction_returns/transaction_test.go
test/projects/relations/relations_test.go

This improves searching for 'FAIL' Go test logs.

refactor(tests): replace word 'fail' in tests

---

README.md

I am suggesting to move the deprecation note into its own section in the README instead of having it as a the main header of it.

docs(readme): adapt deprecation notice

---

.github/workflows/lint.yml
engine/mock/do.go
test/features/if_present/if_present_test.go
test/mock/mock_test.go
test/projects/types/types_test.go

Related to #276.
https://golangci-lint.run/usage/linters/
* `golint` is deprecated (since v1.41.0). Replaced by `revive`.
* `scopelint` is deprecated (since v1.39.0). Replaced by `exportloopref`.

ci(lint): use latest version of golangci-lint

---

runtime/builder/builder.go

I have some flaky tests, and I suspect that the problem lies in the query string generation of the mock. I think the issue could be that [there is a loop](https://github.com/prisma/prisma-client-go/blob/329fe99e3ead0552598689a06710dfe1f545880f/runtime/builder/builder.go#L194) iterating over the `uniques` map, which has no guaranteed order.

fix(mocks): build fields in deterministic order

---

README.md

Use correct link to contributing guide in README.md.

docs(readme): link to correct contributing file in repo

---

binaries/binaries.go

Upgrade prisma to `v5.4.2` with engine hash `ac9d7041ed77bcc8a8dbd2ab6616b39013829574`.

chore(prisma): upgrade prisma to v5.4.2

---

binaries/binaries.go

Upgrade prisma to `v5.5.2` with engine hash `aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a`.

chore(prisma): upgrade prisma to v5.5.2

---

engine/mock/do.go
engine/mock/mock.go
generator/ast/dmmf/dmmf.go
runtime/builder/builder.go
runtime/transaction/transaction.go
test/features/enums/enums_test.go
test/projects/basic/basic_test.go

fix(builder): disallow duplicate fields

---

binaries/version.go
engine/lifecycle.go

Upgrade prisma to `v5.6.0` with engine hash `e95e739751f42d8ca026f6b910f5a2dc5adeaeee`.

chore(prisma): upgrade prisma to v5.6.0

---

binaries/version.go

Upgrade prisma to `v5.7.0` with engine hash `79fb5193cf0a8fdbef536e4b4a159cad677ab1b9`.

chore(prisma): upgrade prisma to v5.7.0

---

binaries/version.go

Upgrade prisma to `v5.7.1` with engine hash `0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5`.

chore(prisma): upgrade prisma to v5.7.1

---

binaries/version.go

Upgrade prisma to `v5.8.0` with engine hash `0a83d8541752d7582de2ebc1ece46519ce72a848`.

chore(prisma): upgrade prisma to v5.8.0

---

binaries/version.go

Upgrade prisma to `v5.8.1` with engine hash `78caf6feeaed953168c64e15a249c3e9a033ebe2`.

chore(prisma): upgrade prisma to v5.8.1

---

binaries/version.go

Upgrade prisma to `v5.9.0` with engine hash `23fdc5965b1e05fc54e5f26ed3de66776b93de64`.

chore(prisma): upgrade prisma to v5.9.0

---

binaries/version.go

Upgrade prisma to `v5.9.1` with engine hash `23fdc5965b1e05fc54e5f26ed3de66776b93de64`.

chore(prisma): upgrade prisma to v5.9.1

---

binaries/version.go

Upgrade prisma to `v5.10.0` with engine hash `5a9203d0590c951969e85a7d07215503f4672eb9`.
Full release notes: [v5.10.0](https://github.com/prisma/prisma/releases/tag/5.10.0).

chore(prisma): upgrade prisma to v5.10.0

---

binaries/version.go

Upgrade prisma to `v5.10.1` with engine hash `5a9203d0590c951969e85a7d07215503f4672eb9`.
Full release notes: [v5.10.1](https://github.com/prisma/prisma/releases/tag/5.10.1).

chore(prisma): upgrade prisma to v5.10.1

---

docs/pages/docs/reference/client/errors.md
generator/templates/actions/create.gotpl
generator/templates/actions/find.gotpl
generator/templates/actions/transaction.gotpl
generator/templates/actions/upsert.gotpl
runtime/transaction/transaction.go

also rename transaction interface

feat(transactions): export transaction types

---

binaries/version.go

Upgrade prisma to `v5.10.2` with engine hash `5a9203d0590c951969e85a7d07215503f4672eb9`.
Full release notes: [v5.10.2](https://github.com/prisma/prisma/releases/tag/5.10.2).

chore(prisma): upgrade prisma to v5.10.2

---

binaries/version.go

Upgrade prisma to `v5.11.0` with engine hash `efd2449663b3d73d637ea1fd226bafbcf45b3102`.
Full release notes: [v5.11.0](https://github.com/prisma/prisma/releases/tag/5.11.0).

chore(prisma): upgrade prisma to v5.11.0

---

binaries/version.go

Upgrade prisma to `v5.12.0` with engine hash `473ed3124229e22d881cb7addf559799debae1ab`.
Full release notes: [v5.12.0](https://github.com/prisma/prisma/releases/tag/5.12.0).

chore(prisma): upgrade prisma to v5.12.0

---

binaries/version.go

Upgrade prisma to `v5.12.1` with engine hash `473ed3124229e22d881cb7addf559799debae1ab`.
Full release notes: [v5.12.1](https://github.com/prisma/prisma/releases/tag/5.12.1).

chore(prisma): upgrade prisma to v5.12.1

---

binaries/version.go

Upgrade prisma to `v5.13.0` with engine hash `b9a39a7ee606c28e3455d0fd60e78c3ba82b1a2b`.
Full release notes: [v5.13.0](https://github.com/prisma/prisma/releases/tag/5.13.0).

chore(prisma): upgrade prisma to v5.13.0

---

binaries/version.go

Upgrade prisma to `v5.14.0` with engine hash `e9771e62de70f79a5e1c604a2d7c8e2a0a874b48`.
Full release notes: [v5.14.0](https://github.com/prisma/prisma/releases/tag/5.14.0).

chore(prisma): upgrade prisma to v5.14.0

---

binaries/version.go

Upgrade prisma to `v5.15.0` with engine hash `12e25d8d06f6ea5a0252864dd9a03b1bb51f3022`.
Full release notes: [v5.15.0](https://github.com/prisma/prisma/releases/tag/5.15.0).

chore(prisma): upgrade prisma to v5.15.0

---

binaries/version.go

Upgrade prisma to `v5.15.1` with engine hash `5675a3182f972f1a8f31d16eee6abf4fd54910e3`.
Full release notes: [v5.15.1](https://github.com/prisma/prisma/releases/tag/5.15.1).

chore(prisma): upgrade prisma to v5.15.1

---

binaries/version.go

Upgrade prisma to `v5.16.0` with engine hash `34ace0eb2704183d2c05b60b52fba5c43c13f303`.
Full release notes: [v5.16.0](https://github.com/prisma/prisma/releases/tag/5.16.0).

chore(prisma): upgrade prisma to v5.16.0

---

binaries/version.go

Upgrade prisma to `v5.16.1` with engine hash `34ace0eb2704183d2c05b60b52fba5c43c13f303`.
Full release notes: [v5.16.1](https://github.com/prisma/prisma/releases/tag/5.16.1).

chore(prisma): upgrade prisma to v5.16.1
