generator/dmmf/dmmf.go, generator/templates/actions/basic.gotpl, generator/test/basic/basic_test.go
This unifies operations find and delete since they work similarly.
=> feat(templates/basic): add delete operation

generator/templates/_header.gotpl, generator/templates/client.gotpl, generator/templates/input.gotpl
The debug mode can be enabled by setting `PHOTON_GO_LOG=debug`.
=> feat(generator): add debug mode

generator/dmmf/dmmf.go, generator/templates/_header.gotpl, generator/templates/actions/actions.gotpl, generator/templates/client.gotpl, generator/templates/input.gotpl, generator/templates/query.gotpl, generator/test/relations/relations_test.go, generator/test/relations/schema.prisma, generator/types/types.go
It's now possible to query for relations! :D
=> feat(query/relations): introduce relations

generator/dmmf/dmmf.go, generator/templates/query.gotpl, generator/test/relations/relations_test.go
This introduces `Some()` and `Every` for n relations, and `Where`
for 1:1 relations.
=> feat(relations): add extra methods to relations

generator/dmmf/dmmf.go, generator/templates/actions/actions.gotpl, generator/templates/enums.gotpl, generator/templates/input.gotpl, generator/templates/query.gotpl, generator/test/types/schema.prisma, generator/test/types/types_test.go
Allows enums:
```prisma
model User {
id   String  @id @default(cuid())
name String
role Role?
}
enum Role {
User
Moderator
Admin
}
```
=> feat(generator): introduce enums

docker/lint.dockerfile, docker/test.dockerfile, generator/templates/actions/find.gotpl, generator/templates/actions/structs.gotpl
=> fix(generator): upgrade to prisma2@alpha; return error on FindOne

generator/templates/_header.gotpl, generator/templates/client.gotpl, runtime/platform/platform.go, runtime/platform/platform_test.go, runtime/runtime.go
use the platform package to find the correct binary to use
=> feat(runtime/platform): introduce runtime and platform package

generator/templates/actions/find.gotpl, generator/templates/actions/structs.gotpl, generator/test/basic/basic_test.go, generator/types/types.go
fix #33. waiting for a published prisma cli with the latest query-engine...
=> fix(generator): map int correctly

generator/templates/actions/find.gotpl, generator/test/pagination/pagination_test.go
add:
- skip
- first
- last
- before
- after
=> feat(query): add pagination methods

README.md, generator/dmmf/dmmf.go
=> docs(readme): add basic setup and api docs

generator/templates/_header.gotpl, generator/templates/input.gotpl, generator/test/basic/basic_test.go
this checks for all pointer types separately
=> fix(tpl/input): improve input conversion

generator/templates/actions/find.gotpl, generator/templates/query.gotpl, generator/test/basic/basic_test.go, generator/test/types/types_test.go, main.go, runtime/platform/platform.go
- add spacing to some templates
- adapt logs
- add enum query test
- add test case for raw json output
=> refactor(misc): minor fixes

README.md
- fix optional fields
- adapt spacing
- add a few default TimeDate fields
=> docs(readme): adapt readme

generator.go, main.go
This uses bufio.Reader instead of bufio.Scanner, as Scanner is error-prone and can't handle bigger payloads.
fix #54
=> fix(generator): use bufio.Reader instead of Scanner

.dockerignore, .github/workflows/integration.sh, .github/workflows/push-integration-test-all.yml, docker/integration.dockerfile, docker/lift.dockerfile, docker/lift.sh, integration/README.md, integration/go.mod, integration/main.go, integration/schema.prisma
This adds a full docker integration test to check if the
runtime binary fetching works out of the box.
continuation of https://github.com/prisma/photongo/pull/61
=> test(integration): add full runtime binary test

binaries/binaries.go, cli/cli.go, engine/lifecycle.go, generator/run.go, generator/test/binaries/binaries_test.go
internal note: rebase into master
=> Fix various things

generator/test/types/schema.prisma
=> test(types): add second enum to ensure it works

binaries/binaries.go, engine/lifecycle.go, logger/logger.go
=> fix(binaries): rename warn->info, print info binary download

.github/workflows/release-draft.yml
=> ci(workflows): fix release drafter config file

generator/dmmf/dmmf.go, generator/templates/actions/actions.gotpl, generator/templates/actions/create.gotpl, generator/templates/actions/find.gotpl, generator/templates/models.gotpl, generator/templates/query.gotpl, generator/test/relations/relations_test.go
=> feat(client): implement With() syntax

generator/templates/actions/actions.gotpl, generator/templates/query.gotpl, generator/test/types/schema.prisma, generator/test/types/types_test.go, generator/types/types.go
=> fix(generator): allow generic field formatting

engine/lifecycle.go, generator/builder/builder.go, generator/raw/raw.go, generator/templates/_header.gotpl, generator/templates/client.gotpl, generator/test/basic/basic_test.go
fix #88 
https://github.com/prisma/prisma-client-go/blob/9c6822d20e7c631177ae6670df13fa79aa76eab1/generator/test/basic/basic_test.go#L698-L712
=> feat(client): add raw sql api

generator/templates/query.gotpl, test/projects/relations/relations_test.go, test/projects/relations/schema.prisma
=> fix(query): adapt casing for some field cases

generator/templates/actions/find.gotpl, generator/templates/query.gotpl, test/projects/relations/relations_test.go, test/projects/relations/schema.prisma
=> fix(query): use relation name on To-structs

docs/reference/raw.md, engine/lifecycle.go, engine/request.go, generator/builder/builder.go, generator/raw/raw.go, generator/templates/actions/create.gotpl, generator/templates/actions/find.gotpl, generator/templates/query.gotpl
=> feat(runtime): add timing logs in debug mode

main.go
Reverts prisma/prisma-client-go#147
=> revert(main): warn when running the bare module

generator/templates/query.gotpl
Re-use Set and fix SetOptional for list types.
=> fix(query): simplify SetOptional

binaries/binaries.go, binaries/publish.sh, generator/raw/execute_raw.go, generator/raw/query_raw.go, generator/raw/raw.go, test/databases/mysql/raw/raw_test.go, test/databases/postgresql/raw/raw_test.go, test/databases/sqlite/raw/raw_test.go
This splits Raw into QueryRaw and ExecuteRaw.
=> chore(prisma): upgrade to prisma 2.0.0-beta.9

generator/dmmf/dmmf.go, generator/templates/query.gotpl, test/features/composite_key_conflict/default_test.go, test/features/composite_key_conflict/schema.prisma
=> fix(query): match compound keys to model

README.md, docs/advanced.md, docs/deploy.md, docs/quickstart.md
=> docs(all): refactor docs

binaries/binaries.go, binaries/binaries_test.go, binaries/bindata/bindata.go, engine/port.go, generator/builder/builder.go, generator/builder/transform.go, generator/dmmf/dmmf.go, generator/runtime/types.go, generator/templates/actions/find.gotpl, generator/templates/query.gotpl, test/databases/postgresql/raw/raw_test.go, test/features/composite_unique_relations/schema.prisma
=> chore(prisma): upgrade prisma to 2.7.1

generator/templates/actions/find.gotpl, generator/templates/errors.gotpl, test/projects/basic/basic_test.go, test/projects/errors/errors_test.go, test/projects/errors/schema.prisma
- improve error handling in general
- return ErrNotFound for Update and Delete as well
=> fix(find): improve error handling

docs/advanced.md, docs/quickstart.md, docs/reference/03-filters.md
Unifies markdown snippets formatting using 4 spaces step.
=> fix: formatting within markdown snippets

.github/semantic.yaml
This enables checking the PR title only for semantic commit messages.
=> ci(semantic): add semantic pr config

.github/release-drafter.yml
- note about starring the repo & tweet template
- feedback note
=> ci(release-drafter): update release template

generator/raw/execute_raw.go
remove a leftover of `data` (#279)
=> fix(raw): adapt result struct

binaries/binaries.go, binaries/publish.sh, engine/lifecycle.go, generator.go, generator/dmmf/dmmf.go, generator/templates/query.gotpl, test/databases/mysql/raw/raw_test.go, test/projects/types/types_test.go
=> feat(prisma): upgrade to 2.10.1

.github/release-drafter.yml
=> ci(release-drafter): switch to minor versions

.github/workflows/integration-test.yml, .github/workflows/lint-pr.yaml, .github/workflows/lint.yml, .github/workflows/test.yml
Reverts prisma/prisma-client-go#321
=> ci(github): revert ignoring docs folder

generator/dmmf/dmmf.go, generator/templates/actions/find.gotpl, test/projects/basic/basic_test.go, test/queries/findfirst/findfirst_test.go, test/queries/findfirst/schema.prisma
=> feat(query): add FindFirst method

docs/advanced.md, docs/quickstart.md, docs/reference/02-find.md, docs/reference/04-fetch.md, docs/reference/08-update.md, docs/reference/09-delete.md, docs/reference/12-json.md, docs/reference/14-mocks.md, docs/reference/README.md, generator/dmmf/dmmf.go, generator/templates/actions/find.gotpl, generator/templates/query.gotpl, test/databases/postgresql/array/array_test.go, test/features/composite/default_test.go, test/features/composite_unique_relations/default_test.go, test/features/if_present/if_present_test.go, test/features/json/default_test.go, test/features/link_many/link_test.go, test/features/number_operations/default_test.go, test/features/table_casing/default_test.go, test/integration/main.go, test/mock/mock_test.go, test/projects/basic/basic_test.go, test/projects/errors/errors_test.go, test/projects/relations/relations_test.go, test/projects/types/types_test.go
=> fix(query): deprecate FindOne, replace with FindUnique

binaries/binaries.go, engine/engine.go, engine/mock/do.go, engine/protocol.go, engine/request.go, generator/templates/_header.gotpl, generator/templates/actions/create.gotpl, generator/templates/actions/find.gotpl, generator/templates/client.gotpl, generator/templates/mock.gotpl, generator/transaction/transaction.go, runtime/builder/builder.go, runtime/transaction/transaction.go, test/features/transaction/schema.prisma, test/features/transaction/transaction_test.go, test/projects/binaries/binaries_test.go, test/projects/binaries/schema.prisma
blocked by https://github.com/prisma/prisma-engines/issues/1431
fix #237
=> feat(client): add transactions [wip]

generator/templates/actions/find.gotpl, test/features/exec_internal/exec_internal_test.go, test/features/exec_internal/schema.prisma
=> feat(query): add ExecInner for find queries

generator/templates/actions/actions.gotpl, generator/templates/actions/create.gotpl, generator/templates/actions/find.gotpl, generator/templates/mock.gotpl, generator/templates/query.gotpl, runtime/transaction/transaction.go, test/features/exported_builder_fields/default_test.go, test/features/exported_builder_fields/schema.prisma
=> feat(client): export builder interfaces

runtime/raw/execute_raw.go, runtime/raw/query_raw.go, test/features/transaction_raw/schema.prisma, test/features/transaction_raw/transaction_test.go
=> feat(transaction): support raw queries in transaction

generator/templates/actions/find.gotpl, test/projects/relations/relations_test.go
=> fix(fetch): allow fetching with update/delete

engine/request.go
=> fix(engine): remove debug logs

generator/templates/query.gotpl, test/features/if_present/if_present_test.go, test/features/if_present/schema.prisma
=> fix(query): allow empty links to use with IfPresent

generator/templates/actions/upsert.gotpl, test/features/upsert/schema.prisma, test/features/upsert/upsert_test.go
=> feat(upsert): add upsert

generator/templates/actions/find.gotpl, generator/templates/query.gotpl, test/projects/relations/relations_test.go, test/projects/relations/schema.prisma, test/projects/types/types_test.go, test/queries/findfirst/findfirst_test.go
=> fix(query): use AND queries to allow duplicate fields

generator/templates/query.gotpl, test/databases/postgresql/array/array_test.go
=> fix(query): adapt postgres array query type

engine/engine.go
=> fix(engine): set http timeout to 0

generator/templates/_header.gotpl, generator/types/types.go, runtime/types/types.go, test/types/bigint/default_test.go, test/types/bigint/schema.prisma
=> feat(client): introduce BigInt type

generator/templates/_header.gotpl, go.mod, go.sum, runtime/types/types.go, test/types/bigint/default_test.go, test/types/decimal/default_test.go, test/types/decimal/schema.prisma
=> feat(client): introduce Decimal type

generator/templates/actions/find.gotpl, generator/templates/actions/upsert.gotpl, test/types/json/default_test.go
=> fix(json): adapt internal json update handling

generator/templates/query.gotpl, test/projects/relations/relations_test.go
=> fix(query): add arguments to unlink

generator/dmmf/dmmf.go
=> feat(generator): add AND operator

generator/templates/actions/actions.gotpl, generator/templates/query.gotpl
=> fix(query): adapt default param struct name

README.md
Please finish this :-) 
Getting:
```
--- FAIL: TestUpsert (42.43s)
--- FAIL: TestUpsert/create (20.80s)
--- FAIL: TestUpsert/create/mysql (0.76s)
mysql.go:41: command docker [exec -t go-client-mysql mysql --user=root --password=pw --execute=CREATE DATABASE go_client_db_kzxazvb] failed: exit status 1
--- FAIL: TestUpsert/create/postgresql (0.71s)
postgresql.go:41: command docker [exec -t go-client-postgres psql -U postgres -c CREATE DATABASE go_client_db_ipizjyn] failed: exit status 1
--- FAIL: TestUpsert/update (11.64s)
--- FAIL: TestUpsert/update/mysql (0.51s)
mysql.go:41: command docker [exec -t go-client-mysql mysql --user=root --password=pw --execute=CREATE DATABASE go_client_db_yfxxlsp] failed: exit status 1
--- FAIL: TestUpsert/update/postgresql (0.42s)
postgresql.go:41: command …
```
=> docs(readme): start documenting how to test

docs/quickstart.md
since 0.8.0 no need more --preview-featuere tag for push db
=> docs(quickstart): remove --preview-feature flag

docs/quickstart.md
=> docs(quickstart): adapt code example import path

generator/templates/_header.gotpl, runtime/lifecycle/lifecycle.go
=> fix(header): add no-op imports for go modules

engine/lifecycle.go
=> fix(engine): recommend running generate on QE mismatch

generator/dmmf/dmmf.go, generator/templates/actions/create.gotpl, generator/templates/actions/find.gotpl, generator/templates/actions/transaction.gotpl, generator/templates/actions/upsert.gotpl, test/features/transaction_returns/transaction_test.go
=> fix(transactions): return batch result for non-unique ops

engine/lifecycle.go, generator/templates/_header.gotpl, go.mod, go.sum
=> feat(lifecycle): load dot-env files before connecting

generator/dmmf/dmmf.go
=> fix(create): do not require list fields on create

docs/reference/README.md
=> docs(reference): rename incorrectly named page in readme

docs/quickstart.md
Fixes https://github.com/prisma/prisma-client-go/issues/542
=> docs(readme): add info about setting output folder and package name

binaries/binaries.go, generator/dmmf/dmmf.go
=> feat(prisma): upgrade prisma to 2.30.0

generator/ast/dmmf/dmmf.go, generator/ast/transform/enums.go, generator/ast/transform/readfilters.go, generator/templates/_header.gotpl, generator/templates/actions/find.gotpl, generator/templates/enums.gotpl, generator/templates/query.gotpl, runtime/types/types.go, test/projects/pagination/pagination_test.go
deprecate existing ones, i.e. direction, in favor of new
internal enums provided in the dmmf
=> feat(enums): use internal prisma enums

docs/features/casing.md
=> docs(features): add case sensitivity docs

README.md
https://github.com/prisma/prisma-client-go/issues/707
=> docs(readme): add note about maintenance status

binaries/publish.sh
=> ci(publish): adapt pkg targets to x64 & arm64

.github/workflows/e2e-test.yml, test/e2e/data-proxy-engine-type-env/default_test.go, test/e2e/data-proxy-url-env/default_test.go, test/e2e/data-proxy-url-schema/default_test.go
=> test(e2e): skip data proxy tests

binaries/binaries.go
=> feat(cli): use new x64 prefix binaries

binaries/binaries.go
=> fix(binaries): use new cloudfront distribution URL

generator/templates/models.gotpl, generator/types/types.go, test/projects/basic/basic_test.go, test/projects/relations/relations_test.go
=> fix(models): do not return empty fields

binaries/binaries.go
=> fix(binaries): revert to 4.7.1

.github/workflows/publish-cli.yml, binaries/README.md, binaries/publish-latest.sh, binaries/publish.sh
=> ci(publish-cli): automate CLI publishing process

.github/workflows/publish-cli.yml
aws is already pre-installed on github actions
=> ci(publish-cli): fix install script

.github/workflows/publish-cli.yml
=> ci(publish-cli): pause auto-publish CLI

binaries/platform/platform.go, binaries/platform/platform_test.go
kinda following
https://github.com/prisma/prisma/blob/8e19c755484dd8bafcad6da12f03ae227543faf3/packages/get-platform/src/getPlatform.ts#L238-L246
and
https://github.com/prisma/prisma/blob/8e19c755484dd8bafcad6da12f03ae227543faf3/packages/get-platform/src/getPlatform.ts#L262-L282
=> fix(platform): add extra check for openssl 3.0.x

.github/workflows/integration-test.yml
see https://github.com/actions/runner-images/issues/8104
=> ci(integration): temp fix for macOS action bug

.idea/misc.xml, generator/ast/dmmf/dmmf.go, generator/run.go, generator/templates/actions/create.gotpl, generator/templates/actions/upsert.gotpl, generator/templates/query.gotpl, test/features/composite_id/composite_id_test.go, test/features/composite_id/schema.prisma
=> fix(composite): support composite primary key in create ops

generator/generator.go, generator/templates/client.gotpl, test/projects/basic/schema.prisma
=> fix(generator): escape datamodel schema

engine/transform.go, test/databases/postgresql/raw_types_custom/raw_test.go, test/databases/postgresql/raw_types_custom/schema.prisma
=> fix(engine): transform arrays for postgres raw query support

.github/workflows/publish-cli.yml, binaries/publish.sh
=> ci(publish-cli): use macos m1 runner for arm64 compat

engine/lifecycle.go, engine/qe.go, engine/request.go, generator.go, generator/generator.go, generator/templates/client.gotpl, test/databases/sqlite/checks_nested/default_test.go, test/databases/sqlite/checks_nested/prisma/exports.go, test/databases/sqlite/checks_nested/prisma/schema.prisma, test/databases/sqlite/checks_path/default_test.go, test/databases/sqlite/checks_path/schema.prisma
=> feat(generator): sanitize connection URL for sqlite relative dirs

docs/pages/docs/reference/_meta.json, docs/pages/docs/reference/client/lifecycle.md, docs/pages/docs/reference/client/options.md
=> docs(client): add client ref docs with options

generator/ast/transform/index.go, generator/ast/transform/models.go
They were fixed by other changes.
Reverts #1135 / e97ad542a6d52fe836a88921d804c11e83c15e41
=> fix(ast): undo primary key changes

engine/lifecycle.go, engine/lifecycle_unix.go, engine/lifecycle_windows.go
=> fix(lifecycle): prevent signal forwarding

test/misc/goroutines/default_test.go
Added error handling with proper panic message
for failed User.FindUnique execution in the
goroutines test.
=> fix(tests): handle error in goroutines test
